name: Performance Test Sorting Algorithms

on:
  push:
    branches:
      - main
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  test-performance:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install pytest # Change this to pytest since we are using it in the test script
    - name: Run performance tests
      run: pytest ./test_sorting.py  # Changed to use pytest to run your performance tests
