name: Performance Test Sorting Algorithms

on:
  push:
    branches:
      - main
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:  # This line allows you to manually trigger the workflow from the GitHub UI

jobs:
  test-performance:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install pytest
²
    - name: Run performance tests for bubble_sort
      continue-on-error: true
      run: pytest -s ./test_sorting.py::test_sort_performance[bubble_sort]

    - name: Run performance tests for quick_sort
      continue-on-error: true
      run: pytest -s ./test_sorting.py::test_sort_performance[quick_sort]
